### PR TITLE
Tile examples

### PR DESCRIPTION
**Pull request by NickFitz**
Pushing these updates to various examples over now so they're available.

### CODE REVIEW

**Comment by nchan0154** [comment]
@NickFitz I think Tomtom does support custom tiles? [''There are no technical limitations to use any external WMS service.''](https://developer.tomtom.com/maps-sdk-web/functional-examples#wms) Forgive me if I'm misunderstanding the context, I haven't pulled your code down to look at it since I figured it probably won't work on localhost.

**Comment by NickFitz** [comment]
@nchan0154 Ah, good catch! Somehow I missed that example; I'll have another go :-)

**Comment by NickFitz** [comment]
@nchan0154 I've spent a while playing with TomTom and as far as I can tell, it only supports [WMS](https://en.wikipedia.org/wiki/Web_Map_Service) services, not [TMS](https://en.wikipedia.org/wiki/Tile_Map_Service), the latter being what the tile repos provide. As I can't (without digging a bit, and maybe not then) see how to emulate a WMS endpoint using plain old files-in-GitHub Pages, I'm leaving this to one side for now :-(

**Comment by nchan0154** [comment]
Thanks for letting me know! I'll update the capabilities assessment with that limitation. @NickFitz

**Comment by AmeliaBR** [comment]
Thanks Nick (& thanks for the tip to dig further, Nic).

Haven't played around with the new examples yet, but either way I think this is an improvement, so merging into master.

**Pull request merged**
