### PR TITLE
Update code blocks for the example pages

### PR DESCRIPTION
**Pull request by Malvoz**
- [x] Use the more appropriate `<code>` element as opposed to `<div>` for blocks of code.
- [x] Update styles for the code blocks, see screenshots below for quick comparison.

<hr>

### New look:

WDYT?

### CODE REVIEW

**Comment by AmeliaBR** [comment]
Apologies for the delay in reviewing!

So, my first instinct was that `<code><script>...` looks weird, I guess because I mentally think of `<code>` as an inline element and script as a block. But, it's no different than `<code><pre>` considering that we are actually displaying the script as a pre-formatted block. So yes, let's keep it semantic and then we can keep it consistent between the snippets that are using the `<script>` as the actual code block versus those that are simply displaying code.

And making the HTML snippets into a single copy-pasteable code block makes sense.

Would it make the styling any easier to make the HTML examples be `<code><pre>` so that there is the same nesting structure as `<code><script>`? Then you could skip the styles for the padding & margin cancelling each other out.

Otherwise, I think this is good to merge.

**Comment by Malvoz** [comment]
Yeah the CSS for cancelling out padding and margin isn't the prettiest, what I should've done was simply set different padding for `.html-example` and `.script-example`, they need to be different because currently the only HTML examples we're doing is for the Static Maps page and they're script-generated so there's no natural white-space from indentation/line breaks adding to spacing as it does with the script examples elsewhere. But if we do introduce example HTML code that aren't script-generated then there'll be a discrepancy in spacing between that and the Static Maps example HTML code.

I think the easiest way to apply different padding in these different scenarios is to 1) set a common padding for `.script-example` and `.html-example` and 2) add a special selector for the Static Maps page where the example code is script-generated? We could mimic `@document url()` at-rule functionality by adding e.g. `<html id="m4h-static-map">`, that way we can do `#m4h-static-map .html-example { /* special padding */ }` for static-map.html?

Or we just set different padding for `.html-example` and `.script-example` now, and deal with discrepancies between script-generated and non-script generated example HTML code later if we ever introduce the latter?

**Comment by Malvoz** [comment]
> Or we just set different padding for `.html-example` and `.script-example` now, and deal with discrepancies between script-generated and non-script generated example HTML code later if we ever introduce the latter?

I opted for this in https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/pull/211/commits/c9d8c03be5d38a6fd9e13d43f8901d4b5757aee9 because I think it's better than what I initially proposed (negative margins). Let me know if we should do it differently. ^^

**Comment by AmeliaBR** [comment]
OK, yeah, that works. As you say, can always tweak it later as needed. No need trying to anticipate problems we don't have. And I might still completely rewrite the static map example page anyway.

I'm going to squash all the tweaks into one commit, thanks again.

**Pull request merged**
