### PR TITLE
Add a few more a11y-related specs & docs

### PR DESCRIPTION
**Pull request by Malvoz**
This PR adds:

- https://www.w3.org/WAI/RD/wiki/Accessible_Maps
- https://w3c.github.io/apa/media-accessibility-reqs/
- https://w3c.github.io/apa/fast/
- https://w3c.github.io/apa/fast/checklist.html

I'm not sure how useful they are so please do review the documents :)

### CODE REVIEW

**Comment by Malvoz** [comment]
Not at all Peter, please do! Note that the RD WG transitioned to "a Task Force" (which one I'm not sure) under the [APA WG](https://www.w3.org/WAI/APA/), as indicated in this [mailing list message](https://lists.w3.org/Archives/Public/public-wai-rd/2015Jul/0011.html).

**Comment by Malvoz** [comment]
> RD WG transitioned to "a Task Force" (which one I'm not sure)

@prushforth 

I believe this to be the [Research Questions Accessibility Task Force (RQTF)](https://www.w3.org/WAI/APA/task-forces/research-questions/). Would you perhaps want to reach out to that Task Force directly?

FWIW, in https://lists.w3.org/Archives/Public/public-rqtf/2018Feb/0003.html they mention accessible web maps in regards to Augmented Reality (which hasn't been discussed in this report yet, should we open an issue for that?).

**Comment by prushforth** [comment]
> Would you perhaps want to reach out to that Task Force directly?

Yes, I'll do that.  Thanks for digging up the linkage.  Probably better to go to the group instead of spamming individuals anyway.

> should we open an issue for that?

Sure, I will send the group a link to that.  Go ahead and make an issue that you feel fits our project but invites ideas from others in the AR space.

**Comment by Malvoz** [comment]
Opened https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/135 for the AR use case. :)

**Comment by AmeliaBR** [comment]
(BTW, thanks for this PR. I'm waiting until I have time to take a look at the links before I can review properly!)

**Comment by Malvoz** [comment]
[WAI Personalization](https://www.w3.org/WAI/personalization/) is relevant as well.

And it's very much about user preferences so I wonder if there should be a use case about user preferences in general in conjunction to - or instead of https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#use-case-color-scheme? Should there be a use case for every relevant user preference? (I suspect we'll see a lot more in terms of user preferences on the web in the future.)

**Comment by AmeliaBR** [comment]
Merged! In https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/commit/fa0ed305b36dafbb76814d6fc49d3eb6e6049e40

(GitHub isn't recognizing it as being from this PR, even though I followed their command line instructions exactly. Something got messed up in waiting 7 months to merge the PR!)

But thanks again Robert for the great suggestions. I kept all the references, just changed the wording around a bit & had a bit of a fight with ReSpec over errors in the referencing notation.

**Pull request closed without merging**
