### PR TITLE
Capability: Pan, Zoom and Re-centre a Map

### PR DESCRIPTION
**Pull request by NickFitz**
This branch isn't ready for merging yet, but I'm adding this PR for it in case anybody has any comments while I'm working on these capabilities.

### CODE REVIEW

**Comment by NickFitz** [comment]
I'll remove this one's "Draft" status now as although it still has nothing in the "Related Specs" section, I'm having trouble thinking of any at the moment, and it's better if it's at least open for review :-)

**Comment by Malvoz** [comment]
In the "Related specs" section, I believe we should reference the CSS primitive proposal of "per-element panning and zooming": https://github.com/w3c/csswg-drafts/issues/5275.

**Comment by NickFitz** [comment]
> In the "Related specs" section, I believe we should reference the CSS primitive proposal of "per-element panning and zooming": [w3c/csswg-drafts#5275](https://github.com/w3c/csswg-drafts/issues/5275).

Ah, thanks - I'll review that and see about adding it.

**Comment by NickFitz** [comment]
I've added a link to the CSS-WG proposal as suggested by @Malvoz. (I'm not aware of, and couldn't find, any Respec way of adding a reference to a GitHub issue, so I've just put a normal link in there.)

**Pull request merged**
