### PR TITLE
[Examples] API keys: Update mapkitstatic referrer

### PR DESCRIPTION
**Pull request by Malvoz**

### CODE REVIEW

**Comment by AmeliaBR** [comment]
@NickFitz, I'll leave this up to you to approve & merge. I assume this was merely an oversight from #207, but this is a good time to make sure that there are no other errors.

**Comment by AmeliaBR** [comment]
OK, I'm going to merge this & then we'll see if it fixes or breaks anything. (What with it being all about URLs, I'm not confident that a local test will prove anything!)

**Comment by Malvoz** [comment]
It shouldn't break anything, but it also seems this didn't fix the [static maps example for MapKit](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/examples/static-map.html#mapkit). :(
Most likely an update is needed in the account itself.

**Comment by AmeliaBR** [comment]
Ah, thanks for checking @Malvoz, I've opened a dedicated issue in #212 & I'll get in touch with Nick F to see if he has time to debug. Otherwise, I might need to set up some new API keys for the project & start from scratch.

Sigh… the worst part is knowing that authentication issues for accessing proprietary data are one thing we can't ever expect to 100% standardize away. Keeping map data up to date will always cost money & that means companies want to get paid.

**Comment by Malvoz** [comment]
> Sigh… the worst part is knowing that authentication issues for accessing proprietary data are one thing we can't ever expect to 100% standardize away. Keeping map data up to date will always cost money & that means companies want to get paid.

Agreed, but I definitely think there are benefits in standardization, for one thing, Map API keys issue could perhaps utilize the Reporting API, making it easier for developers to retrieve notifications. Or how things should behave on the client when an API key has expired, for example Bings Maps API is displaying _some_ information, although developer-oriented (fails due to localhost in this instance):



where other map tools would just cease to function silently:

**Pull request merged**
