### PR TITLE
Add responsiveness to example pages + screenshot figures to the spec

### PR DESCRIPTION
**Pull request by Malvoz**
I thought it'd be nice to have responsive maps in the examples. It allows people to test the capabilities of the example maps on their mobile phones as they'd expect them to look on any given website today (I noted that Google _requires_ using 2 fingers to interact with maps on mobile, yuck!).

And while it may look like there's much to this PR, most of the additions & deletions are just coming from indentation fixes.

The big change is how custom scripts are added to the document, while before it was:

```HTML
<script class="example">
  ...
</script>
```

now it's:

```HTML
<div class="script-example">
  <script>
    ...
  </script>
</div>
```

to allow for scrolling the overflow.

Also, there are quite some changes to [`examples.css`](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/commit/54f9b1e8dc169688d49de5b676d2f94dab8166a8#diff-60f38247cf42073ad9e5ab85fbceebf7), e.g. to prevent the inherited controls and custom controls from overlapping, and to restrict maps from being wider than a 100% of the viewport.

We haven't discussed doing this at all prior to this PR; but I thought it'd be fun to do and while there are still things to be done this seems pretty solid. If y'all don't want to do this I'm okay with that.

You can compare the live examples to those hosted on **raw.githack.com**, by resizing the viewport etc, see for example:
- [create-map.html](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/examples/create-map.html) ([live](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/examples/create-map.html))
- [add-custom-control.html](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/examples/add-custom-control.html) ([live](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/examples/add-custom-control.html))
- [multiple-location-markers.html](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/examples/multiple-location-markers.html) ([live](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/examples/multiple-location-markers.html))
- [set-view-zoom.html](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/examples/set-view-zoom.html) ([live](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/examples/set-view-zoom.html))

(Some embeds fail on raw.githack.com because it's unauthorized.)

### CODE REVIEW

**Comment by NickFitz** [comment]
+1 from me.

**Comment by Malvoz** [comment]
Please note that I added screenshot figures (as proposed in https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/35) in this very same PR because Github doesn't like me, or well actually because I suck.

View the screenshots (again, hosted on raw.githack.com) here:

- [Display an interactive map within a web page](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/index.html#use-case-create-map)
- [Display a map centered on a point location](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/index.html#use-case-single-location)
- [Display multiple point locations as map markers](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/index.html#use-case-multiple-location-markers)
- [Display custom imagery as a map layer](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/index.html#use-case-custom-map)
- [Provide alternative map layers which the user can select](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/index.html#use-case-alternative-layers)
- [Display drawings or schematics without geographic coordinates](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/index.html#use-case-technical-drawings)
- [Add a custom control to a map](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/index.html#use-case-add-custom-control)
- [Control which layers are currently visible & which can be hidden by the user](https://raw.githack.com/Malvoz/HTML-Map-Element-UseCases-Requirements/master/index.html#use-case-set-layer-visibility)

**Comment by AmeliaBR** [comment]
I've just merged in @NickFitz's example updates, so that's creating merge conflicts. If either of you have time to clean that up, it'd be great. Otherwise, I'll run through them later in the week when I'm back home.

Beyond that, both of these changes are definitely welcome. (Even if they'd ideally be 2 PRs. But we've all been there with Git.) I'd been kind of thinking that we'd just create a dedicated use case / example set for "responsive map size", but you're right that it's better to be able to check out the responsiveness of individual features and interaction patterns.

**Comment by Malvoz** [comment]
Thanks @AmeliaBR, I was expecting the merge conflicts, I have resolved them now.

> I'd been kind of thinking that we'd just create a dedicated use case / example set for "responsive map size"

I think that's definitely a use case to address - it's not all that straight forward for some of the reference tools, do you want to open an issue for that or should I?

**Comment by AmeliaBR** [comment]
> I think that's definitely a use case to address - it's not all that straight forward for some of the reference tools, do you want to open an issue for that or should I?

I started an issue in #174, but additional details/thoughts would be welcome!

Thanks again for the commits!

**Pull request merged**
